"""empty message

Revision ID: 1266756da04a
Revises: 
Create Date: 2021-07-07 23:25:45.204945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1266756da04a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    op.drop_table('association')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('password', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.create_table('association',
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], )
    )
    op.create_table('project',
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('manager_id', sa.INTEGER(), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    # ### end Alembic commands ###
