"""empty message

Revision ID: bb8cd17dd2cd
Revises: 17e56eb8ceae
Create Date: 2021-07-13 20:27:16.298468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb8cd17dd2cd'
down_revision = '17e56eb8ceae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.drop_table('user')
    op.drop_table('task')
    op.drop_table('project')
    op.drop_table('association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], )
    )
    op.create_table('project',
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.VARCHAR(length=400), nullable=True),
    sa.Column('manager_id', sa.INTEGER(), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('task',
    sa.Column('task_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.VARCHAR(length=300), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('password', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###
